name: Factions
author: Taylor
description: Factions core.

api: 5.0.0
version: 1.0.0
main: taylor\factions\Main

depend:
  - DEVirion

permissions:
  commands.pay:
    default: true
  commands.givecurrency:
    default: op
  commands.my:
    default: true