name: Factions
author: Taylor
description: Factions core.

api: 5.0.0
version: 1.0.0
main: taylor\factions\Main

depend:
  - DEVirion # Required to run libasynql.

permissions:
  commands.pay:
    default: true
  commands.givecurrency:
    default: op
  commands.my:
    default: true
  commands.kits:
    default: true
  commands.kitsmanager:
    default: op
  commands.permission:
    default: op
  commands.group:
    default: op
  commands.faction:
    default: true